- name: install head-node
  sudo: True
  hosts: all
  tasks:
    - name: install apt packages
      apt: pkg={{ item }}  update_cache=yes cache_valid_time=3600
      with_items:
        - acpi
        - ant
        - apt-file
        - atop
        - autoconf
        - autoconf-doc
        - automake
        - axel
        - bc
        - bcrypt
        - binutils-doc
        - bison
        - bison-doc
        - blast2
        - build-essential
        - cdecl
        - check
        - cmake
        - cmake-curses-gui
        - cpanminus
        - cpp-doc
        - cpuset
        - cream
        - cutils
        - cvs
        - cvs-buildpackage
        - daemon
        - dc
        - ddd
        - ddd-doc
        - debconf-doc
        - debian-goodies
        - discover
        - discover-data
        - dos2unix
        - dsh
        - eclipse
        - enscript
        - ess
        - evince
        - expect
        - flex
        - freeglut3
        - freeglut3-dev
        - gawk
        - gawk-doc
        - gbase
        - gcc-4.6
        - gcc-doc
        - gdb-doc
        - geany
        - geany-plugin-addons
        - gedit
        - gfortran
        - git
        - git-cvs
        - git-gui
        - git-svn
        - glibc-doc
        - gnupg-agent
        - gnuplot
        - gnuplot-doc
        - graphviz
        - gsasl
        - gv
        - help2man
        - hfsplus
        - hfsprogs
        - iftop
        - inkscape
        - iotop
        - iperf
        - ipmitool
        - ispell
        - jpegoptim
        - kcachegrind
        - ksh
        - kstart
        - latexdiff
        - lftp
        - libaio-dev
        - libargtable2-0
        - libatlas3gf-base
        - libatlas-base-dev
        - libatlas-dev
        - libbz2-dev
        - libc6-dev-i386
        - libc6-i386
        - libclone-pp-perl
        - libconfig-file-perl
        - libconfig-inifiles-perl
        - libcpuset1
        - libcurl4-openssl-dev
        - libdatetime-perl
        - libdb1-compat
        - libdbd-mysql-perl
        - libdbd-pg-perl
        - libdbd-sqlite3-perl
        - libdbi-perl
        - libexpect-perl
        - libffi-dev
        - libfftw3-3
        - libfftw3-dev
        - libfuse-dev
        - libg20
        - libgcj-common
        - libgd2-xpm-dev
        - libgdbm-dev
        - libgraphviz-dev
        - libgsl0-dev
        - libgsl0ldbl
        - libgtk2.0-0
        - libgtk2.0-bin
        - libgtk2.0-cil
        - libgtk2.0-common
        - libgtk2.0-dev
        - libhdf5-serial-dev
        - libjpeg62
        - libjson-xs-perl
        - liblapack3gf
        - liblapack-dev
        - liblist-moreutils-perl
        - liblzma5
        - liblzma-dev
        - liblzo2-2
        - liblzo2-dev
        - libmono-system-core4.0-cil
        - libmpc-dev
        - libmpfr-dev
        - libmysqlclient-dev
        - libncurses5-dev
        - libnet-daemon-perl
        - libnl1
        - libnss-db
        - libopenmpi-dev
        - libpam0g-dev
        - libparse-recdescent-perl
        - libperl-dev
        - libplrpc-perl
        - libpq5
        - libpq-dev
        - libpstreams-dev
        - libreadline-dev
        - libsasl2-dev
        - libsdl1.2debian
        - libset-scalar-perl
        - libsgutils2-2
        - libsprng2
        - libsqlite3-dev
        - libsvm3
        - libterm-readkey-perl
        - libtiff4-dev
        - libtool
        - libtool-doc
        - libtre5
        - libxdot4
        - libxml2-dev
        - libxml-dom-perl
        - libxml-libxml-perl
        - libxml-libxslt-perl
        - libxml-parser-perl
        - libxml-regexp-perl
        - libxml-simple-perl
        - libxmpi4c2
        - libxmu-dev
        - libxmu-headers
        - libyaml-dev
        - make
        - make-doc
        - mbuffer
        - mcelog
        - mcrypt
        - meld
        - mercurial
        - mpack
        - mutt
        - mysql-client
        - ncftp
        - ncompress
        - ncurses-dev
        - ncurses-term
        - nedit
        - netpipe-tcp
        - nfs-common
        - nss-updatedb
        - numactl
        - octave-epstk
        - octave-pkg-dev
        - openmpi-bin
        - openmpi-common
        - optipng
        - p7zip-full
        - pbzip2
        - pdftk
        - pdksh
        - pep8
        - perl-doc
        - php5-cli
        - php5-common
        - pigz
        - plink
        - pmount
        - pngcrush
        - portreserve
        - primer3
        - pv
        - pwgen
        - pychecker
        - pylint
        - python-biopython
        - python-biopython-doc
        - python-biopython-sql
        - python-dev
        - python-libxml2
        - python-openssl
        - python-pika
        - python-scipy
        - python-tables
        - python-tk
        - python-virtualenv
        - qt4-dev-tools
        - quota
        - reiserfsprogs
        - reportbug
        - ruby
        - ruby-mysql
        - sasl2-bin
        - screen
        - sharutils
        - snmp
        - socat
        - sqlitebrowser
        - sqliteman
        - stress
        - swig
        - swig-doc
        - sysstat
        - tcl8.4-dev
        - tcl8.5-dev
        - tcl-dev
        - telnet-ssl
        - texlive
        - texlive-bibtex-extra
        - texlive-fonts-extra
        - texlive-font-utils
        - texlive-lang-greek
        - texlive-latex3
        - texlive-latex-base
        - texlive-latex-extra
        - texlive-math-extra
        - texlive-pictures
        - texlive-pstricks
        - texlive-publishers
        - tidy
        - tk8.4-dev
        - tk8.5-dev
        - tkcvs
        - tklib
        - tofrodos
        - traceroute
        - units
        - unixodbc
        - unixodbc-dev
        - unp
        - valgrind
        - wamerican
        - wbritish
        - wbritish-huge
        - whois
        - winpdb
        - xbase-clients
        - xemacs21
        - xfonts-100dpi
        - xfonts-75dpi
        - xfonts-base
        - xfsdump
        - xpdf
        - xsltproc
        - xutils-dev
        - xvfb
        - yasm
        - zip
    - group: name=openlava state=present
    - user: name=openlava shell=/bin/bash group=openlava system=yes  createhome=no state=present
    - unarchive: src=/tmp/openlava.tar.gz dest=/opt copy=no group=openlava owner=openlava
