- name: install head-node
  sudo: True
  hosts: all
  tasks:
    - hostname: name=cloud-head
    - name: install apt packages
      apt: pkg={{ item }}  update_cache=yes cache_valid_time=3600
      with_items:
        - nfs-kernel-server
    - lineinfile: dest=/etc/exports line="/home *(rw,no_root_squash,no_subtree_check)" create=yes
